import test from "node:test";
import assert from "node:assert/strict";
import { createAccountCenterServer } from "./server.js";

test("local control panel serves an accessible application shell", async () => {
  const app = createAccountCenterServer({ token: "test-token" });
  const address = await app.listen();
  try {
    const response = await fetch(`http://127.0.0.1:${address.port}/`);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /<main/);
    assert.match(html, /Account Center/);
    assert.match(html, /aria-live/);
    assert.match(html, /Connected accounts/);
    assert.match(html, /Attention &amp; pending work/);
    assert.match(html, /View guided auth/);
    assert.match(html, /ArrowRight/);
    assert.match(html, /ArrowLeft/);
    assert.match(html, /tabindex="0" aria-selected="true"/);
    assert.match(html, /tab.tabIndex = selected \? 0 : -1/);
    assert.match(html, /Launch token rejected/);
    assert.match(html, /Readable/);
    assert.doesNotMatch(html, /'online'/);
    assert.match(html, /Guided auth/);
    assert.match(html, /Receipts &amp; audit/);
    assert.match(html, /data-view="dashboard"/);
    assert.match(html, /\/api\/auth-challenges/);
    assert.match(html, /\/api\/capabilities/);
    assert.match(html, /function renderOperatorActions/);
    assert.match(html, /action && action.reason/);
    assert.match(html, /\/api\/audit/);
    assert.match(html, /<label for="audit-outcome">Outcome<\/label>/);
    assert.match(html, /Filter audit history/);
    assert.match(html, /function loadAudit\(\)/);
    assert.match(html, /URLSearchParams/);
    assert.match(html, /\/api\/models/);
    assert.match(html, /\/api\/scopes/);
    assert.match(html, /Capability discovery/);
    assert.match(html, /authorization: 'Bearer ' \+ token.value/);
    assert.match(html, /Cancel pending challenge/);
    assert.match(html, /View challenge details/);
    assert.match(html, /id="guided-detail"/);
    assert.match(html, /function loadChallengeDetail\(id\)/);
    assert.match(html, /\/api\/auth-challenges\/.*encodeURIComponent\(id\)/);
    assert.match(html, /Guided-auth challenge detail could not be verified/);
    assert.match(html, /function scopeLabel\(scope\)/);
    assert.match(html, /scope not reported/);
    assert.match(html, /id="context-selector"/);
    assert.match(html, /<label for="runtime-scope">Runtime &amp; scope<\/label>/);
    assert.match(html, /No readable scopes are available\./);
    assert.match(html, /function renderContextSelector\(scopeData, scopesUnavailable\)/);
    assert.match(html, /selectedContext = runtimeScope.value/);
    assert.match(html, /Context changed\. Refreshing observed runtime data/);
    assert.match(html, /\/api\/auth-challenges\/.*encodeURIComponent\(id\).*\/cancel/);
    assert.match(html, /credentials: 'same-origin'/);
    assert.match(html, /UNPROVEN — data unavailable/);
    assert.match(html, /Retry workspace data/);
    assert.match(html, /some evidence is UNPROVEN/);
    assert.match(html, /--prose:system-ui/);
    assert.match(html, /--technical:ui-monospace/);
    assert.match(html, /\.primary,\.quiet\{min-height:44px/);
    assert.match(html, /\.field input,\.field select\{width:100%;min-height:44px/);
    assert.match(html, /\.tab\{min-height:44px/);
    assert.match(html, /@media\(max-width:760px\).*\.account-records\{grid-template-columns:1fr\}/);
    assert.match(html, /@media\(max-width:430px\).*\.account-details\{grid-template-columns:1fr\}/);
    assert.match(html, /@media\(max-width:320px\)/);
    assert.match(html, /class="account-records" id="accounts" role="list" aria-label="Connected accounts"/);
    assert.match(html, /<dt>Capacity<\/dt>/);
    assert.match(html, /<dt>Proof<\/dt>/);
    assert.match(html, /UNPROVEN — unreadable status/);
    assert.doesNotMatch(html, /localStorage|sessionStorage/);
  } finally {
    await app.close();
  }
});
