import test from "node:test";
import assert from "node:assert/strict";
import { createAccountCenterServer } from "./server.js";

test("local control panel serves an accessible application shell", async () => {
  const app = createAccountCenterServer({ token: "test-token" });
  const address = await app.listen();
  try {
    const response = await fetch(`http://127.0.0.1:${address.port}/`);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /<main/);
    assert.match(html, /Account Center/);
    assert.match(html, /aria-live/);
    assert.match(html, /Connected accounts/);
    assert.match(html, /Attention &amp; pending work/);
    assert.match(html, /View guided auth/);
    assert.match(html, /ArrowRight/);
    assert.match(html, /ArrowLeft/);
    assert.match(html, /tabindex="0" aria-selected="true"/);
    assert.match(html, /tab.tabIndex = selected \? 0 : -1/);
    assert.match(html, /Launch token rejected/);
    assert.match(html, /Readable/);
    assert.doesNotMatch(html, /'online'/);
    assert.match(html, /Guided auth/);
    assert.match(html, /id="guided-freshness"/);
    assert.match(html, /function challengeFreshness\(challengeData\)/);
    assert.match(html, /Server snapshot:/);
    assert.match(html, /Accounts &amp; routing/);
    assert.match(html, /Settings/);
    assert.match(html, /Receipts &amp; audit/);
    assert.match(html, /data-view="dashboard"/);
    assert.match(html, /\/api\/auth-challenges/);
    assert.match(html, /\/api\/capabilities/);
    assert.match(html, /function renderOperatorActions/);
    assert.match(html, /action && action.reason/);
    assert.match(html, /\/api\/audit/);
    assert.match(html, /<label for="audit-outcome">Outcome<\/label>/);
    assert.match(html, /<label for="audit-action">Action category<\/label>/);
    assert.match(html, /id="audit-action" name="action"/);
    assert.match(html, /Filter audit history/);
    assert.match(html, /id="audit-load-more"/);
    assert.match(html, /Load older audit records/);
    assert.match(html, /function loadAudit\(cursor\)/);
    assert.match(html, /parameters\.set\('action', auditAction\.value\)/);
    assert.match(html, /nextCursor/);
    assert.match(html, /URLSearchParams/);
    assert.match(html, /function auditRecord\(item\)/);
    assert.match(html, /Audit ID:/);
    assert.match(html, /Proof:/);
    assert.match(html, /Warnings:/);
    assert.match(html, /Recorded:/);
    assert.match(html, /id="audit-freshness"/);
    assert.match(html, /function auditFreshness\(auditData\)/);
    assert.match(html, /Audit snapshot:/);
    assert.match(html, /function operationRecord\(item\)/);
    assert.match(html, /id="operation-freshness"/);
    assert.match(html, /function operationFreshness\(operationData\)/);
    assert.match(html, /Operation snapshot:/);
    assert.match(html, /Operation ID:/);
    assert.match(html, /Completed:/);
    assert.match(html, /Provider: /);
    assert.match(html, /Runtime: /);
    assert.match(html, /Scope: /);
    assert.match(html, /scope kind not reported/);
    assert.match(html, /id="operation-load-more"/);
    assert.match(html, /Load older protected operations/);
    assert.match(html, /function loadOperations\(cursor\)/);
    assert.match(html, /function selectedScopeKind\(\)/);
    assert.match(html, /parameters\.set\('runtime', runtime\)/);
    assert.match(html, /parameters\.set\('scopeKind', scopeKind\)/);
    assert.match(html, /selected runtime and scope kind/);
    assert.match(html, /operationCursor/);
    assert.match(html, /id="operation-filter"/);
    assert.match(html, /<label for="operation-outcome">Outcome<\/label>/);
    assert.match(html, /Filter operation history/);
    assert.match(html, /operationOutcome\.value/);
    assert.match(html, /No protected operations match this outcome/);
    assert.match(html, /Older protected operations could not be verified/);
    assert.match(html, /Models &amp; fallbacks/);
    assert.match(html, /data-view="models-fallbacks"/);
    assert.match(html, /id="model-policy-state"/);
    assert.match(html, /Requested policy: Not reported/);
    assert.match(html, /Effective runtime model: Not reported/);
    assert.match(html, /Fallback chain: Not reported/);
    assert.match(html, /Model policy is UNPROVEN/);
    assert.match(html, /function renderModelsFallbacks\(modelData, unavailable\)/);
    assert.match(html, /renderModelsFallbacks\(data.models, unavailable.models\)/);
    assert.match(html, /\/api\/models/);
    assert.match(html, /\/api\/limits/);
    assert.match(html, /function renderLimits\(limitData, limitsUnavailable\)/);
    assert.match(html, /renderLimits\(data.limits, unavailable.limits\)/);
    assert.match(html, /function selectedRuntimeQuery\(\)/);
    assert.match(html, /function loadModels\(\)/);
    assert.match(html, /function loadLimits\(\)/);
    assert.match(html, /function loadChallenges\(\)/);
    assert.match(html, /api\('\/api\/models' \+ selectedRuntimeQuery\(\)\)/);
    assert.match(html, /api\('\/api\/limits' \+ selectedRuntimeQuery\(\)\)/);
    assert.match(html, /api\('\/api\/auth-challenges' \+ selectedRuntimeQuery\(\)\)/);
    assert.match(html, /observedProfileCount/);
    assert.match(html, /readableProfileCount/);
    assert.match(html, /runtimeCompatibility/);
    assert.match(html, /UNPROVEN — runtime application is not verified/);
    assert.match(html, /accountRef/);
    assert.match(html, /\/api\/scopes/);
    assert.match(html, /Capability discovery/);
    assert.match(html, /authorization: 'Bearer ' \+ token.value/);
    assert.match(html, /Cancel pending challenge/);
    assert.match(html, /<dialog class="confirmation-dialog" id="cancel-challenge-dialog"/);
    assert.match(html, /aria-labelledby="cancel-challenge-heading" aria-describedby="cancel-challenge-description"/);
    assert.match(html, /This cancels only Account Center's local guided-auth challenge record/);
    assert.match(html, /does not delete or change runtime credentials/);
    assert.match(html, /id="cancel-challenge-dismiss"/);
    assert.match(html, /id="cancel-challenge-confirm"/);
    assert.match(html, /function openCancelChallengeDialog\(id, trigger\)/);
    assert.match(html, /cancelChallengeDialog\.showModal\(\); cancelChallengeHeading\.focus\(\)/);
    assert.match(html, /cancelChallengeDialog\.addEventListener\('cancel'/);
    assert.match(html, /if \(!cancellationInFlight\) closeCancelChallengeDialog\(true\)/);
    assert.match(html, /cancelChallengeDialog\.addEventListener\('keydown'/);
    assert.match(html, /event\.key !== 'Tab'/);
    assert.match(html, /function restoreCancelChallengeFocus\(\)/);
    assert.match(html, /if \(cancellationInFlight\) return/);
    assert.match(html, /openCancelChallengeDialog\(id, button\)/);
    assert.match(html, /View challenge details/);
    assert.match(html, /id="guided-detail"/);
    assert.match(html, /function loadChallengeDetail\(id\)/);
    assert.match(html, /\/api\/auth-challenges\/.*encodeURIComponent\(id\)/);
    assert.match(html, /Guided-auth challenge detail could not be verified/);
    assert.match(html, /function scopeLabel\(scope\)/);
    assert.match(html, /scope not reported/);
    assert.match(html, /id="context-selector"/);
    assert.match(html, /<label for="runtime-scope">Runtime &amp; scope<\/label>/);
    assert.match(html, /No readable scopes are available\./);
    assert.match(html, /function renderContextSelector\(scopeData, scopesUnavailable\)/);
    assert.match(html, /id="context-capability"/);
    assert.match(html, /id="context-chip"/);
    assert.match(html, /function contextCapabilityLabel\(capabilities\)/);
    assert.match(html, /runtimeScope\.hidden = scopes\.length === 1/);
    assert.match(html, /contextChip\.hidden = scopes\.length !== 1/);
    assert.match(html, /selectedContext = runtimeScope.value/);
    assert.match(html, /Context changed\. Refreshing observed runtime data/);
    assert.match(html, /\/api\/auth-challenges\/.*encodeURIComponent\(cancelChallengeId\).*\/cancel/);
    assert.doesNotMatch(html, /\/api\/auth-challenges\/(?:start|complete)/);
    assert.match(html, /credentials: 'same-origin'/);
    assert.match(html, /UNPROVEN — data unavailable/);
    assert.match(html, /Retry workspace data/);
    assert.match(html, /some evidence is UNPROVEN/);
    assert.match(html, /--prose:system-ui/);
    assert.match(html, /--technical:ui-monospace/);
    assert.match(html, /\.primary,\.quiet\{min-height:44px/);
    assert.match(html, /\.field input,\.field select\{width:100%;min-height:44px/);
    assert.match(html, /\.tab\{min-height:44px/);
    assert.match(html, /@media\(max-width:760px\).*\.account-records\{grid-template-columns:1fr\}/);
    assert.match(html, /@media\(max-width:430px\).*\.account-details\{grid-template-columns:1fr\}/);
    assert.match(html, /@media\(max-width:320px\)/);
    assert.match(html, /class="account-records" id="accounts" role="list" aria-label="Connected accounts"/);
    assert.match(html, /<dt>Capacity<\/dt>/);
    assert.match(html, /<dt>Proof<\/dt>/);
    assert.match(html, /UNPROVEN — unreadable status/);
    assert.match(html, /function renderViewState\(target, state, title, detail, actionLabel\)/);
    assert.match(html, /\['loading', 'empty', 'error', 'blocked', 'read-only', 'unproven'\]/);
    assert.match(html, /function renderAccountsRouting\(capabilityData, unavailable\)/);
    assert.match(html, /profile\.runtimeCompatibility\.indexOf\(runtime\) !== -1/);
    assert.match(html, /No connected accounts were reported as compatible with the selected runtime\./);
    assert.match(html, /function renderSettings\(capabilityData, unavailable\)/);
    assert.match(html, /No verified release status reported/);
    assert.match(html, /No release is eligible for Apply/);
    assert.match(html, /Update Center is unavailable/);
    assert.match(html, /renderAccountsRouting\(data.capabilities, unavailable\)/);
    assert.match(html, /renderSettings\(data.capabilities, unavailable\)/);
    assert.doesNotMatch(html, /\/api\/updates/);
    assert.doesNotMatch(html, /localStorage|sessionStorage/);
  } finally {
    await app.close();
  }
});
