import { mkdir, writeFile } from "node:fs/promises";

const [name = "checkpoint", state = "passed"] = process.argv.slice(2);
const generatedAt = new Date().toISOString();
const status = {
  schemaVersion: "account-center.checkpoint.v1",
  generatedAt,
  checkpoint: name,
  state,
  tokenFree: true,
  note: "Generated by Account Center repo scripts; contains no credentials."
};
const gate = {
  schemaVersion: "account-center.gate.v1",
  generatedAt,
  latest: {
    checkpoint: name,
    state
  },
  tokenFree: true
};

await mkdir(".account-center", { recursive: true });
await writeFile(".account-center/status.json", `${JSON.stringify(status, null, 2)}\n`, "utf8");
await writeFile(".account-center/gate.json", `${JSON.stringify(gate, null, 2)}\n`, "utf8");
console.log(`account-center checkpoint ${name}: ${state}`);
